# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoTimeLapse
                                 A QGIS plugin
 creates multitemporal (timelapse) videos from satellite images for a point or area
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-18
        copyright            : (C) 2025 by Cristian Javier Martinez Blanco
        email                : cristianjmb10@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoTimeLapse class from file GeoTimeLapse.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geo_timelapse import GeoTimeLapse
    return GeoTimeLapse(iface)
