from enum import StrEnum


class Token(StrEnum):
    # ------ Background colors --------
    BACKGROUND_WHITE = "BACKGROUND_WHITE"
    BACKGROUND_DISABLED = "BACKGROUND_DISABLED"

    BACKGROUND_BUTTON_PREVIOUS = "BACKGROUND_BUTTON_PREVIOUS"
    BACKGROUND_BUTTON_DISABLED = "BACKGROUND_BUTTON_DISABLED"
    BACKGROUND_BUTTON_HOVER = "BACKGROUND_BUTTON_HOVER"
    BACKGROUND_BUTTON_PREVIOUS_HOVER = "BACKGROUND_BUTTON_PREVIOUS_HOVER"

    COLOR_SEPARATOR_LINE = "COLOR_SEPARATOR_LINE"

    # ------ Text Colors --------
    COLOR_TEXT_PRIMARY = "COLOR_TEXT_PRIMARY"
    COLOR_TEXT_SECONDARY = "COLOR_TEXT_SECONDARY"
    COLOR_TEXT_MUTED = "COLOR_TEXT_MUTED"
    COLOR_TEXT_WHITE = "COLOR_TEXT_WHITE"
    COLOR_TEXT_DISABLED_WHITE = "COLOR_TEXT_DISABLED_WHITE"

    # ------ Brand Colors (QGIS Guide) --------
    COLOR_PRIMARY = "COLOR_PRIMARY"
    COLOR_DARK = "COLOR_DARK"

    COLOR_GREEN_LIGHT_100 = "COLOR_GREEN_LIGHT_100"
    COLOR_GREEN_LIGHT_200 = "COLOR_GREEN_LIGHT_200"
    COLOR_GREEN_LIGHT_300 = "COLOR_GREEN_LIGHT_300"
    COLOR_TEXT_ON_GREEN_LIGHT = "COLOR_TEXT_ON_GREEN_LIGHT"

    COLOR_BORDER_PRIMARY = "COLOR_BORDER_PRIMARY"
    COLOR_BORDER_DISABLED = "COLOR_BORDER_DISABLED"

    # ------ State Colors --------
    COLOR_ACCENT_ORANGE = "COLOR_ACCENT_ORANGE"

    # ------ Typography --------
    FONT_SIZE_TITLE = "FONT_SIZE_TITLE"
    FONT_SIZE_MEDIUM = "FONT_SIZE_MEDIUM"
    FONT_SIZE_BASE = "FONT_SIZE_BASE"
    FONT_SIZE_SMALL = "FONT_SIZE_SMALL"

    FONT_WEIGHT_BOLD = "FONT_WEIGHT_BOLD"
    FONT_WEIGHT_SEMIBOLD = "FONT_WEIGHT_SEMIBOLD"
    FONT_WEIGHT_NORMAL = "FONT_WEIGHT_NORMAL"

    # -------- Border Radius ---------
    BORDER_RADIUS_PAGINATION_BUTTON = "BORDER_RADIUS_PAGINATION_BUTTON"
    BORDER_RADIUS_GENERAL = "BORDER_RADIUS_GENERAL"
    BORDER_RADIUS_CARD = "BORDER_RADIUS_CARD"
